import type { LegalDocument } from "@/types/legal";

/**
 * Terms and Conditions — CampaignX by Botfinity Inc.
 *
 * Transcribed from the approved source document dated 1 September 2026.
 * The wording is the legal text and should not be edited for tone: change
 * it only from an updated source document, and move the `updated` date with
 * it. The all-caps blocks are reproduced as written — capitalisation is how
 * disclaimers and liability limits are made conspicuous, which is a legal
 * requirement in several jurisdictions, not a styling choice.
 */
export const termsOfService: LegalDocument = {
  eyebrow: "Legal",
  title: "Terms and Conditions",
  summary:
    "The agreement between you and Botfinity Inc. governing your access to and use of CampaignX.",
  effective: "1 September 2026",
  updated: "1 September 2026",

  sections: [
    {
      heading: "Acceptance of terms",
      blocks: [
        {
          kind: "text",
          value: [
            { text: "These Terms and Conditions (" },
            { text: '"Terms," "Agreement"', bold: true },
            { text: ") constitute a legally binding agreement between you (" },
            { text: '"User," "you," "your"', bold: true },
            { text: ") and " },
            { text: "Botfinity Inc.", bold: true },
            { text: " (" },
            { text: '"Company," "we," "us," "our"', bold: true },
            {
              text: "), governing your access to and use of the CampaignX platform available at ",
            },
            {
              text: "campaignx.supermia.ai",
              href: "https://campaignx.supermia.ai",
            },
            { text: ", including all associated applications, APIs, tools, and documentation." },
          ],
        },
        {
          kind: "notice",
          value: [
            {
              text: "BY CREATING AN ACCOUNT, ACCESSING, OR USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS AND OUR ",
            },
            { text: "PRIVACY POLICY", href: "/privacy" },
            {
              text: ". IF YOU DO NOT AGREE TO THESE TERMS, YOU MUST NOT ACCESS OR USE THE SERVICE.",
            },
          ],
        },
        {
          kind: "text",
          value: [
            {
              text: "If you are entering into this Agreement on behalf of a company, organization, or other legal entity (",
            },
            { text: '"Organization"', bold: true },
            {
              text: '), you represent and warrant that you have the authority to bind that Organization to these Terms. In such cases, "you" and "your" shall refer to the Organization.',
            },
          ],
        },
      ],
    },

    {
      heading: "Definitions",
      blocks: [
        {
          kind: "definitions",
          items: [
            { term: '"Account"', definition: "means your registered account on the Platform." },
            {
              term: '"AI-Generated Content"',
              definition:
                "means any text, image descriptions, templates, or other content generated by the Platform's artificial intelligence features.",
            },
            {
              term: '"Campaign"',
              definition:
                "means any marketing communication created, managed, or deployed through the Service.",
            },
            {
              term: '"Connected Account"',
              definition:
                "means a Third-Party Platform account linked to your Workspace via OAuth or API credentials.",
            },
            {
              term: '"Content"',
              definition:
                "means any text, images, videos, audio, templates, media files, or other materials uploaded to, created on, or published through the Platform.",
            },
            {
              term: '"Intellectual Property Rights"',
              definition:
                "means all intellectual property rights including patents, copyrights, trademarks, trade secrets, and moral rights.",
            },
            {
              term: '"Subscription"',
              definition: "means the paid plan or tier under which you access the Service.",
            },
            {
              term: '"Third-Party Platform"',
              definition:
                "means any external service integrated with the Platform, including but not limited to Facebook, Instagram, LinkedIn, X (formerly Twitter), WhatsApp, Twilio, email providers, and voice services.",
            },
            {
              term: '"User Content"',
              definition:
                "means all Content that you upload, create, or transmit through the Service, excluding AI-Generated Content.",
            },
            {
              term: '"Workspace"',
              definition:
                "means an organizational unit within the Platform under which your campaigns, connected accounts, and activities are scoped and isolated.",
            },
          ],
        },
      ],
    },

    {
      heading: "Eligibility",
      subsections: [
        {
          heading: "Age requirement",
          blocks: [
            {
              kind: "text",
              value:
                "You must be at least 18 years old, or the age of majority in your jurisdiction, whichever is higher, to create an Account and use the Service. By registering, you represent and warrant that you meet this requirement.",
            },
          ],
        },
        {
          heading: "Entity requirement",
          blocks: [
            {
              kind: "text",
              value:
                "If you use the Service on behalf of an Organization, you represent and warrant that:",
            },
            {
              kind: "list",
              items: [
                "You are authorized to bind the Organization to these Terms",
                "The Organization is duly organized, validly existing, and in good standing under the laws of its jurisdiction",
                "Your use of the Service complies with the Organization's internal policies and applicable laws",
              ],
            },
          ],
        },
        {
          heading: "Prohibited users",
          blocks: [
            { kind: "text", value: "You may not use the Service if:" },
            {
              kind: "list",
              items: [
                "You have been previously suspended or removed from the Service",
                "You are located in a country subject to a comprehensive U.S. government embargo",
                "You are listed on any U.S. government list of prohibited or restricted parties",
              ],
            },
          ],
        },
      ],
    },

    {
      heading: "Account registration and security",
      subsections: [
        {
          heading: "Account creation",
          blocks: [
            {
              kind: "text",
              value:
                "To access the Service, you must create an Account by providing accurate, current, and complete information. You may register using email and password, or Google Single Sign-On (SSO).",
            },
          ],
        },
        {
          heading: "Account responsibilities",
          blocks: [
            { kind: "text", value: "You are solely responsible for:" },
            {
              kind: "list",
              items: [
                "Maintaining the confidentiality of your Account credentials",
                "All activities that occur under your Account",
                [
                  { text: "Promptly notifying us of any unauthorized access or security breach at " },
                  { text: "hello@supermia.ai", href: "mailto:hello@supermia.ai" },
                ],
                "Keeping your Account information up to date",
              ],
            },
          ],
        },
        {
          heading: "Account security",
          blocks: [
            {
              kind: "text",
              value:
                "We implement security measures including password hashing, JWT-based session management, and optional two-factor authentication (2FA). However, no method of electronic transmission or storage is 100% secure, and we cannot guarantee absolute security.",
            },
          ],
        },
        {
          heading: "Multiple workspaces",
          blocks: [
            {
              kind: "text",
              value:
                "Your Account may own and manage multiple Workspaces. Each Workspace operates as an isolated environment with its own campaigns, connected accounts, and data.",
            },
          ],
        },
      ],
    },

    {
      heading: "Service description",
      subsections: [
        {
          heading: "Core features",
          blocks: [
            {
              kind: "text",
              value:
                "CampaignX is an AI-powered multi-channel marketing campaign platform that provides:",
            },
            {
              kind: "list",
              items: [
                [
                  { text: "AI content generation: ", bold: true },
                  {
                    text: "automated creation of marketing content using artificial intelligence across social media posts, email campaigns, SMS, WhatsApp, voice call scripts, and RCS messages.",
                  },
                ],
                [
                  { text: "Multi-channel publishing: ", bold: true },
                  {
                    text: "direct publishing and scheduling of content to connected social media platforms.",
                  },
                ],
                [
                  { text: "Communication deployment: ", bold: true },
                  {
                    text: "sending campaigns through email, SMS, WhatsApp, voice and RCS via integrated providers.",
                  },
                ],
                [
                  { text: "Analytics and insights: ", bold: true },
                  {
                    text: "performance tracking, engagement metrics, audience analytics, and dashboards across all connected platforms.",
                  },
                ],
                [
                  { text: "Media gallery: ", bold: true },
                  {
                    text: "upload, organize, and manage media assets for use in campaigns.",
                  },
                ],
                [
                  { text: "Workspace management: ", bold: true },
                  {
                    text: "organizational isolation of campaigns, accounts, and data.",
                  },
                ],
                [
                  { text: "Calendar and scheduling: ", bold: true },
                  {
                    text: "visual calendar management for planning campaign activities.",
                  },
                ],
                [
                  { text: "Template management: ", bold: true },
                  { text: "creation, storage, and reuse of campaign templates." },
                ],
              ],
            },
          ],
        },
        {
          heading: "AI-powered features",
          blocks: [
            {
              kind: "text",
              value:
                "The Platform uses third-party AI services (including OpenAI, Deepgram, and Cartesia) for content generation, transcription, and speech synthesis. You acknowledge and agree that:",
            },
            {
              kind: "list",
              items: [
                "AI-Generated Content is produced by machine learning models and may not always be accurate, appropriate, or suitable for your specific use case",
                [
                  {
                    text: "You are solely responsible for reviewing, editing, and approving all AI-Generated Content before publication or deployment",
                    bold: true,
                  },
                ],
                "AI outputs may occasionally contain errors, biases, or inappropriate content",
                "We do not guarantee specific outcomes or results from AI-Generated Content",
                "The quality and capabilities of AI features may change as underlying models are updated",
              ],
            },
          ],
        },
        {
          heading: "Third-party integrations",
          blocks: [
            {
              kind: "text",
              value:
                "The Platform integrates with Third-Party Platforms via OAuth 2.0, API keys, and other authentication mechanisms. By connecting a Third-Party Platform:",
            },
            {
              kind: "list",
              items: [
                "You authorize us to access, store, and use the credentials and data necessary to provide the Service",
                "You agree to comply with the terms of service of each connected Third-Party Platform",
                "You acknowledge that Third-Party Platform availability, functionality, and API access are outside our control",
                "Connected Account tokens and credentials are stored securely and used solely for providing the Service",
              ],
            },
          ],
        },
      ],
    },

    {
      heading: "User obligations and acceptable use",
      subsections: [
        {
          heading: "General obligations",
          blocks: [
            { kind: "text", value: "You agree to:" },
            {
              kind: "list",
              items: [
                "Use the Service only for lawful purposes and in compliance with these Terms",
                "Provide accurate and truthful information in your campaigns",
                "Comply with all applicable laws, regulations, and Third-Party Platform policies",
                "Obtain all necessary consents from individuals targeted by your campaigns",
                "Comply with anti-spam legislation (CAN-SPAM, GDPR, PECR, CASL, and equivalent local laws) for all communication channels",
              ],
            },
          ],
        },
        {
          heading: "Prohibited conduct",
          blocks: [
            {
              kind: "text",
              value: [{ text: "Content restrictions. ", bold: true }, { text: "You shall not:" }],
            },
            {
              kind: "list",
              items: [
                "Create, store, distribute, or publish Content that is unlawful, defamatory, obscene, pornographic, harassing, threatening, hateful, or discriminatory",
                "Generate spam, unsolicited bulk messages, or phishing communications",
                "Distribute malware, viruses, or other harmful software",
                "Create Content that infringes any third party's Intellectual Property Rights",
                "Promote illegal activities, substances, or services",
                "Distribute misleading, deceptive, or fraudulent content",
              ],
            },
            {
              kind: "text",
              value: [{ text: "Technical restrictions. ", bold: true }, { text: "You shall not:" }],
            },
            {
              kind: "list",
              items: [
                "Attempt to gain unauthorized access to the Service, other users' accounts, or our infrastructure",
                "Reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code of the Platform",
                "Use automated scripts, bots, or scrapers to access the Service, except through our authorized APIs",
                "Interfere with or disrupt the Service, servers, or networks connected to the Service",
                "Circumvent any security, rate-limiting, or access control measures",
                "Use the Service to benchmark or build a competing product",
              ],
            },
            {
              kind: "text",
              value: [
                { text: "Compliance restrictions. ", bold: true },
                { text: "You shall not:" },
              ],
            },
            {
              kind: "list",
              items: [
                "Violate the terms of service of any connected Third-Party Platform",
                "Exceed the rate limits, quota limits, or usage policies of connected Third-Party Platforms",
                "Impersonate any person or entity or misrepresent your affiliation with any person or entity",
                "Collect or harvest personal data of individuals without their explicit consent",
              ],
            },
          ],
        },
        {
          heading: "Campaign compliance",
          blocks: [
            {
              kind: "text",
              value:
                "You are solely responsible for ensuring that all campaigns created and deployed through the Service comply with:",
            },
            {
              kind: "list",
              items: [
                "Applicable advertising and marketing laws, including FTC guidelines, ASA codes, and equivalent regulations",
                "Industry-specific regulations, for example healthcare, finance and education",
                "Third-Party Platform advertising policies and community standards",
                "Data protection and privacy laws (GDPR, CCPA, CAN-SPAM, and others)",
                "Consumer protection laws",
              ],
            },
          ],
        },
      ],
    },

    {
      heading: "Intellectual property",
      subsections: [
        {
          heading: "Platform ownership",
          blocks: [
            {
              kind: "text",
              value:
                "The Service, including all software, algorithms, AI models (to the extent developed by us), user interfaces, designs, documentation, trademarks, and other Intellectual Property Rights therein, are and remain the exclusive property of Botfinity Inc. or its licensors. Nothing in these Terms grants you any ownership rights in the Platform.",
            },
          ],
        },
        {
          heading: "Your content",
          blocks: [
            {
              kind: "text",
              value: [
                {
                  text: "You retain all Intellectual Property Rights in your User Content. By uploading or creating Content on the Platform, you grant us a ",
                },
                {
                  text: "non-exclusive, worldwide, royalty-free, sublicensable license",
                  bold: true,
                },
                {
                  text: " to use, store, reproduce, modify, and display your User Content solely for the purpose of providing and improving the Service. This license terminates when you delete your Content or close your Account, except for:",
                },
              ],
            },
            {
              kind: "list",
              items: [
                "Content already published to Third-Party Platforms, which is governed by those platforms' terms",
                "Anonymized, aggregated data derived from your Content used for Service improvement",
                "Backup copies retained for a reasonable period in accordance with our data retention policies",
              ],
            },
          ],
        },
        {
          heading: "AI-Generated Content",
          blocks: [
            {
              kind: "list",
              items: [
                [
                  { text: "You are granted a " },
                  { text: "non-exclusive, worldwide license", bold: true },
                  {
                    text: " to use, modify, publish, and distribute AI-Generated Content created through your use of the Service for your business purposes.",
                  },
                ],
                "You acknowledge that similar or identical AI-Generated Content may be produced for other users.",
                "We do not claim ownership of AI-Generated Content but retain the right to use anonymized patterns for model improvement.",
                [
                  { text: "You are solely responsible", bold: true },
                  {
                    text: " for ensuring that your use of AI-Generated Content does not infringe third-party rights.",
                  },
                ],
              ],
            },
          ],
        },
        {
          heading: "Feedback",
          blocks: [
            {
              kind: "text",
              value: [
                {
                  text: "If you provide us with feedback, suggestions, or ideas regarding the Service (",
                },
                { text: '"Feedback"', bold: true },
                {
                  text: "), you grant us an unrestricted, irrevocable, non-exclusive, royalty-free right to use, modify, and incorporate such Feedback into the Service without any obligation to you.",
                },
              ],
            },
          ],
        },
      ],
    },

    {
      heading: "Subscriptions, payments and billing",
      subsections: [
        {
          heading: "Subscription plans",
          blocks: [
            {
              kind: "text",
              value:
                "Access to certain features of the Service may require a paid Subscription. Details of available plans, pricing, and features are available on our website or within the Platform.",
            },
          ],
        },
        {
          heading: "Payment terms",
          blocks: [
            {
              kind: "list",
              items: [
                "All fees are quoted and payable in United States Dollars (USD) unless otherwise specified",
                "Payments are processed through our designated payment processor",
                "Subscription fees are billed in advance on a monthly or annual basis, as selected by you",
                "All fees are non-refundable except as expressly provided in these Terms or required by applicable law",
              ],
            },
          ],
        },
        {
          heading: "Automatic renewal",
          blocks: [
            {
              kind: "text",
              value:
                "Subscriptions automatically renew at the end of each billing cycle unless you cancel before the renewal date. We will notify you of any price changes at least 30 days before they take effect.",
            },
          ],
        },
        {
          heading: "Taxes",
          blocks: [
            {
              kind: "text",
              value:
                "All fees are exclusive of applicable taxes, including VAT, GST, sales tax, and withholding tax. You are responsible for all applicable taxes, and we may add taxes to your invoice as required by law.",
            },
          ],
        },
        {
          heading: "Late payment",
          blocks: [
            { kind: "text", value: "If payment is not received by the due date:" },
            {
              kind: "list",
              items: [
                "We may suspend your access to the Service after providing 7 days written notice",
                "Outstanding amounts may accrue interest at the rate of 1.5% per month, or the maximum rate permitted by law, whichever is lower",
                "We reserve the right to engage collection agencies or pursue legal remedies",
              ],
            },
          ],
        },
      ],
    },

    {
      heading: "Data processing and privacy",
      subsections: [
        {
          heading: "Privacy Policy",
          blocks: [
            {
              kind: "text",
              value: [
                {
                  text: "Our collection, use, and protection of your Personal Data is governed by our ",
                },
                { text: "Privacy Policy", href: "/privacy" },
                { text: ", which is incorporated into these Terms by reference." },
              ],
            },
          ],
        },
        {
          heading: "Data Processing Agreement",
          blocks: [
            {
              kind: "text",
              value: [
                {
                  text: "Where you are a Data Controller and we process Personal Data on your behalf, for example customer contact data used in campaigns, the terms of our Data Processing Agreement (DPA) shall apply. A DPA is available on request at ",
                },
                { text: "hello@supermia.ai", href: "mailto:hello@supermia.ai" },
                { text: "." },
              ],
            },
          ],
        },
        {
          heading: "Your data obligations",
          blocks: [
            { kind: "text", value: "You represent and warrant that:" },
            {
              kind: "list",
              items: [
                "You have obtained all necessary consents and authorizations to upload and process any Personal Data through the Service",
                "Your use of the Service complies with applicable data protection laws",
                "You will not upload sensitive or special category data (health, racial or ethnic origin, political opinions, religious beliefs, biometric data) unless you have obtained explicit consent and adequate safeguards are in place",
              ],
            },
          ],
        },
      ],
    },

    {
      heading: "Third-party services and platforms",
      subsections: [
        {
          heading: "Third-party terms",
          blocks: [
            {
              kind: "text",
              value:
                "Your use of Third-Party Platforms through the Service is subject to those platforms' own terms of service, privacy policies, and usage guidelines. You agree to review and comply with all applicable Third-Party Platform terms.",
            },
          ],
        },
        {
          heading: "No endorsement",
          blocks: [
            {
              kind: "text",
              value:
                "Our integration with Third-Party Platforms does not constitute an endorsement of those platforms or their services. We are not responsible for:",
            },
            {
              kind: "list",
              items: [
                "The availability, accuracy, or reliability of Third-Party Platforms",
                "Changes to Third-Party Platform APIs, policies, or terms that may affect the Service",
                "Actions taken by Third-Party Platforms regarding your accounts, such as suspension, rate limiting, or content removal",
              ],
            },
          ],
        },
        {
          heading: "API changes",
          blocks: [
            {
              kind: "text",
              value:
                "Third-Party Platforms may modify, deprecate, or discontinue their APIs at any time. We will make reasonable efforts to adapt to such changes but cannot guarantee uninterrupted integration functionality.",
            },
          ],
        },
      ],
    },

    {
      heading: "Service availability and support",
      subsections: [
        {
          heading: "Service availability",
          blocks: [
            {
              kind: "text",
              value:
                "We strive to maintain 99.9% uptime for the Service but do not guarantee uninterrupted access. The Service may be temporarily unavailable due to:",
            },
            {
              kind: "list",
              items: [
                "Scheduled maintenance, with reasonable advance notice",
                "Unplanned outages, system failures, or force majeure events",
                "Third-Party Platform outages or API disruptions",
                "Security incidents requiring immediate response",
              ],
            },
          ],
        },
        {
          heading: "Modifications to the Service",
          blocks: [
            {
              kind: "text",
              value:
                "We reserve the right to modify, update, suspend, or discontinue any part of the Service at any time. For material changes that adversely affect your use:",
            },
            {
              kind: "list",
              items: [
                "We will provide at least 30 days advance notice",
                "You may terminate your Subscription and receive a pro-rated refund for the unused portion",
              ],
            },
          ],
        },
        {
          heading: "Support",
          blocks: [
            {
              kind: "text",
              value: [
                { text: "Support is available via email at " },
                { text: "hello@supermia.ai", href: "mailto:hello@supermia.ai" },
                {
                  text: ". Response times and support levels may vary based on your Subscription plan.",
                },
              ],
            },
          ],
        },
      ],
    },

    {
      heading: "Disclaimers",
      subsections: [
        {
          heading: '"As is" disclaimer',
          blocks: [
            {
              kind: "notice",
              value:
                "THE SERVICE IS PROVIDED \"AS IS\" AND \"AS AVAILABLE\" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO: IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT; WARRANTIES OF ACCURACY, RELIABILITY, OR COMPLETENESS OF AI-GENERATED CONTENT; WARRANTIES THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE; AND WARRANTIES REGARDING THE RESULTS OBTAINABLE FROM THE USE OF THE SERVICE.",
            },
          ],
        },
        {
          heading: "AI content disclaimer",
          blocks: [
            {
              kind: "notice",
              value:
                "AI-GENERATED CONTENT IS PROVIDED FOR INFORMATIONAL AND CREATIVE PURPOSES ONLY. WE DO NOT WARRANT THAT AI-GENERATED CONTENT IS ACCURATE, COMPLETE, NON-INFRINGING, OR SUITABLE FOR ANY PARTICULAR PURPOSE. YOU ACKNOWLEDGE THAT AI MODELS MAY PRODUCE CONTENT THAT IS INCORRECT, BIASED, OR INAPPROPRIATE, AND YOU ASSUME ALL RISK ASSOCIATED WITH YOUR USE OF AI-GENERATED CONTENT.",
            },
          ],
        },
        {
          heading: "Third-party disclaimer",
          blocks: [
            {
              kind: "text",
              value:
                "We are not responsible for any losses, damages, or liabilities arising from your use of Third-Party Platforms, services, or content accessed through the Service.",
            },
          ],
        },
      ],
    },

    {
      heading: "Limitation of liability",
      subsections: [
        {
          heading: "Exclusion of damages",
          blocks: [
            {
              kind: "notice",
              value:
                "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL BOTFINITY INC., ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES; LOSS OF PROFITS, REVENUE, DATA, BUSINESS OPPORTUNITIES, OR GOODWILL; COST OF PROCUREMENT OF SUBSTITUTE SERVICES; OR DAMAGES ARISING FROM UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA. THIS APPLIES WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.",
            },
          ],
        },
        {
          heading: "Liability cap",
          blocks: [
            {
              kind: "notice",
              value:
                "OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE GREATER OF (A) THE TOTAL FEES PAID BY YOU TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED UNITED STATES DOLLARS (USD $100.00).",
            },
          ],
        },
        {
          heading: "Exceptions",
          blocks: [
            {
              kind: "text",
              value: "The limitations in this section shall not apply to:",
            },
            {
              kind: "list",
              items: [
                "Liability arising from our gross negligence or willful misconduct",
                "Liability that cannot be excluded or limited under applicable law, such as death or personal injury caused by negligence",
                "Your obligation to pay fees owed under these Terms",
                "Either party's indemnification obligations",
              ],
            },
          ],
        },
      ],
    },

    {
      heading: "Indemnification",
      subsections: [
        {
          heading: "Your indemnification",
          blocks: [
            {
              kind: "text",
              value:
                "You agree to indemnify, defend, and hold harmless Botfinity Inc. and its officers, directors, employees, agents, and affiliates from and against any and all claims, losses, damages, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from or relating to:",
            },
            {
              kind: "list",
              items: [
                "Your use of the Service",
                "Your User Content or campaigns deployed through the Service",
                "Your violation of these Terms or any applicable law or regulation",
                "Your violation of any Third-Party Platform's terms of service",
                "Your infringement of any third party's Intellectual Property Rights",
                "Claims by recipients of your campaigns, including spam complaints, privacy violations, and consumer protection claims",
              ],
            },
          ],
        },
        {
          heading: "Indemnification procedure",
          blocks: [
            { kind: "text", value: "We will:" },
            {
              kind: "list",
              items: [
                "Promptly notify you of any claim subject to indemnification",
                "Provide you with reasonable cooperation in the defense of such claim",
                "Allow you to control the defense and settlement of such claim, provided that no settlement shall impose any obligation on us without our prior written consent",
              ],
            },
          ],
        },
      ],
    },

    {
      heading: "Termination",
      subsections: [
        {
          heading: "Termination by you",
          blocks: [
            {
              kind: "text",
              value: [
                { text: "You may terminate your Account and these Terms at any time by contacting us at " },
                { text: "hello@supermia.ai", href: "mailto:hello@supermia.ai" },
                { text: ", or by deleting your Account through the Platform settings where available." },
              ],
            },
          ],
        },
        {
          heading: "Termination by us",
          blocks: [
            {
              kind: "text",
              value:
                "We may suspend or terminate your Account and access to the Service immediately, with or without notice, if:",
            },
            {
              kind: "list",
              items: [
                "You breach any material provision of these Terms",
                "You engage in prohibited conduct",
                "We are required to do so by law or regulatory authority",
                "You fail to pay any fees due under your Subscription",
                "Your use of the Service poses a security risk to the Platform or other users",
                "We discontinue the Service, with 30 days' advance notice",
              ],
            },
          ],
        },
        {
          heading: "Effect of termination",
          blocks: [
            { kind: "text", value: "Upon termination:" },
            {
              kind: "list",
              items: [
                "Your right to access and use the Service ceases immediately",
                "We will delete your Account data within 90 days, except as required by law or our data retention policies",
                "All licenses granted to you under these Terms terminate",
                "You remain liable for any fees accrued prior to termination",
                "The sections covering intellectual property, disclaimers, limitation of liability, indemnification, governing law and dispute resolution survive termination",
              ],
            },
          ],
        },
        {
          heading: "Data export",
          blocks: [
            {
              kind: "text",
              value: [
                {
                  text: "Upon request made within 30 days of termination, we will provide you with an export of your User Content in a commonly used, machine-readable format. Requests should be sent to ",
                },
                { text: "hello@supermia.ai", href: "mailto:hello@supermia.ai" },
                { text: "." },
              ],
            },
          ],
        },
      ],
    },

    {
      heading: "Governing law",
      subsections: [
        {
          heading: "Applicable law",
          blocks: [
            {
              kind: "text",
              value: [
                {
                  text: "These Terms and any disputes arising out of or in connection with them shall be governed by and construed in accordance with the ",
                },
                { text: "laws of the State of Delaware, United States", bold: true },
                { text: ", without regard to its conflict of law provisions." },
              ],
            },
          ],
        },
        {
          heading: "International users",
          blocks: [
            {
              kind: "text",
              value:
                "If you access the Service from outside the United States, you are responsible for compliance with local laws. Nothing in these Terms shall deprive you of any mandatory consumer protection rights afforded to you under the laws of your country of residence.",
            },
          ],
        },
      ],
    },

    {
      heading: "Dispute resolution",
      subsections: [
        {
          heading: "Informal resolution",
          blocks: [
            {
              kind: "text",
              value: [
                {
                  text: "Before initiating formal dispute resolution, you agree to first contact us at ",
                },
                { text: "hello@supermia.ai", href: "mailto:hello@supermia.ai" },
                { text: " and attempt to resolve any dispute informally for at least 30 days." },
              ],
            },
          ],
        },
        {
          heading: "Binding arbitration",
          blocks: [
            {
              kind: "text",
              value: [
                { text: "If informal resolution is unsuccessful, any dispute, controversy, or claim arising out of or relating to these Terms or the Service shall be resolved by " },
                { text: "binding arbitration", bold: true },
                {
                  text: " administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules. The arbitration shall be conducted in the State of Delaware, United States, or by video conference at the arbitrator's discretion.",
                },
              ],
            },
          ],
        },
        {
          heading: "Class action waiver",
          blocks: [
            {
              kind: "notice",
              value:
                "YOU AGREE TO RESOLVE DISPUTES WITH US ON AN INDIVIDUAL BASIS ONLY. YOU WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS ACTION, COLLECTIVE ACTION, OR REPRESENTATIVE PROCEEDING, WHETHER AS A NAMED PLAINTIFF, CLASS MEMBER, OR OTHERWISE.",
            },
          ],
        },
        {
          heading: "Exceptions",
          blocks: [
            { kind: "text", value: "The following claims are exempt from arbitration:" },
            {
              kind: "list",
              items: [
                "Claims eligible for small claims court",
                "Claims for injunctive or equitable relief relating to Intellectual Property Rights",
                "Emergency relief to prevent imminent harm",
              ],
            },
          ],
        },
        {
          heading: "Jurisdiction for non-arbitrable claims",
          blocks: [
            {
              kind: "text",
              value:
                "For any claims not subject to arbitration, you consent to the exclusive jurisdiction of the federal and state courts located in the State of Delaware, United States.",
            },
          ],
        },
      ],
    },

    {
      heading: "General provisions",
      blocks: [
        {
          kind: "definitions",
          items: [
            {
              term: "Entire agreement.",
              definition:
                "These Terms, together with the Privacy Policy and any applicable Subscription agreements or DPAs, constitute the entire agreement between you and Botfinity Inc. regarding the Service, superseding all prior agreements, understandings, and communications.",
            },
            {
              term: "Severability.",
              definition:
                "If any provision of these Terms is found to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect. The invalid provision shall be modified to the minimum extent necessary to make it valid and enforceable.",
            },
            {
              term: "Waiver.",
              definition:
                "No waiver of any provision of these Terms shall be deemed a further or continuing waiver of such provision or any other provision. Our failure to enforce any right or provision shall not constitute a waiver of that right or provision.",
            },
            {
              term: "Assignment.",
              definition:
                "You may not assign or transfer your rights or obligations under these Terms without our prior written consent. We may assign our rights and obligations without restriction. Any attempted assignment in violation of this section shall be null and void.",
            },
            {
              term: "Force majeure.",
              definition:
                "We shall not be liable for any failure or delay in performance due to causes beyond our reasonable control, including acts of God, natural disasters, pandemics, war, terrorism, government actions, power failures, internet disruptions, or Third-Party Platform outages.",
            },
            {
              term: "Notices.",
              definition:
                "All legal notices to us should be sent to hello@supermia.ai. Notices to you will be sent to the email address associated with your Account. You are responsible for ensuring your Account email address is current and accurate.",
            },
            {
              term: "Headings.",
              definition:
                "Section headings are for convenience only and shall not affect the interpretation of these Terms.",
            },
            {
              term: "Relationship of the parties.",
              definition:
                "Nothing in these Terms shall be construed to create a partnership, joint venture, agency, or employment relationship between you and Botfinity Inc.",
            },
            {
              term: "Export compliance.",
              definition:
                "You agree to comply with all applicable U.S. and international export control and trade sanctions laws, including the Export Administration Regulations (EAR) and sanctions administered by the Office of Foreign Assets Control (OFAC).",
            },
          ],
        },
      ],
    },

    {
      heading: "Changes to these Terms",
      blocks: [
        {
          kind: "text",
          value:
            "We reserve the right to modify these Terms at any time. When we make material changes:",
        },
        {
          kind: "list",
          items: [
            'We will update the "Last updated" date at the top of these Terms',
            "We will provide notice via email or a prominent notice on the Platform at least 30 days before the changes take effect",
            "Your continued use of the Service after the effective date of the modified Terms constitutes your acceptance of the changes",
            "If you do not agree to the modified Terms, you must stop using the Service and may terminate your Account",
          ],
        },
      ],
    },

    {
      heading: "Contact information",
      blocks: [
        {
          kind: "text",
          value: [
            { text: "If you have any questions about these Terms, contact Botfinity Inc. at " },
            { text: "hello@supermia.ai", href: "mailto:hello@supermia.ai" },
            { text: " or visit " },
            {
              text: "campaignx.supermia.ai",
              href: "https://campaignx.supermia.ai",
            },
            { text: "." },
          ],
        },
      ],
    },
  ],

  closing:
    "By using CampaignX, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. © 2026 Botfinity Inc. All rights reserved.",
};
