/**
 * Campaign creative, served from this project.
 *
 * These are real assets CampaignX generated. They were originally hot-linked
 * from S3, which meant every visitor fetched 26 full-size 1024x1024 PNGs
 * (43MB) from a third-party host on every load, with no chance for Next to
 * optimise them and an outage there taking the gallery down with it.
 *
 * They now live in `public/images/gallery`, resized to 640px and encoded as
 * WebP — the same set at 2MB, which is what the dome actually needs given it
 * renders them as small tiles.
 *
 * This is the single source for them. Import `galleryImages` rather than
 * writing paths inline, so adding or reordering artwork is one edit here.
 */

/** How many files sit in `public/images/gallery`, named `campaign-NN.webp`. */
const COUNT = 26;

/**
 * Artwork present on disk but kept off the site.
 *
 * The files stay in `public/images/gallery` so the numbering never shifts —
 * renumbering to close a gap would silently repoint every entry after it.
 * Listing the number here is what removes it from the gallery.
 *
 * 06 — a python coiled around a dollar sign; reads as a threat, not an offer.
 * 09 — a kite tangled with a stethoscope; the metaphor does not land.
 */
const EXCLUDED: readonly number[] = [6, 9];

export interface GalleryImage {
  readonly src: string;
  readonly alt: string;
}

/**
 * Generated rather than hand-listed: the files are sequentially named, so a
 * literal array would be near-identical lines that drift out of sync with
 * the directory the moment one is added.
 */
export const galleryImages: readonly GalleryImage[] = Array.from(
  { length: COUNT },
  (_, index) => index + 1,
)
  .filter((number) => !EXCLUDED.includes(number))
  .map((number, position) => ({
    src: `/images/gallery/campaign-${String(number).padStart(2, "0")}.webp`,
    /* Deliberately generic. These are decorative samples in a gallery that
       already carries its own heading; describing each one would be
       inventing detail about artwork that changes. */
    alt: `Campaign creative generated by CampaignX, example ${position + 1}`,
  }));

/** Just the paths, for consumers that take a plain string list. */
export const galleryImageSrcs: readonly string[] = galleryImages.map(
  (image) => image.src,
);
